### ISSUE TITLE
Builds not reliable

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-opt-in-out#137]
Took 3 attempts to ship:-
- 424 - https://circleci.com/gh/Financial-Times/next-opt-in-out/424
- 425 - https://circleci.com/gh/Financial-Times/next-opt-in-out/425
- 426 - https://circleci.com/gh/Financial-Times/next-opt-in-out/426

**Comment by wheresrhys** [comment]
I have a feeling there are one or tow tests where responses from ft.com (used in mdot optin) are not mocked

**Comment by adambraimbridge** [comment]
Looks like one problem is the test for opting out. 10% of the time it opts out, but immediately back in, because it randomly falls into the forced-opt-in-anonymous 10% bucket.

There are two cookies, set when opting out, that prevent any chance of being immediately forced back in. But the tests are run on a different domain than ft.com, so those cookies are not accessible. I'm not sure what the solution is in this case.

**Comment by matthew-andrews** [comment]
has anyone looked at the akamai rule?

**Comment by wheresrhys** [comment]
builds schmilds
